import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    appName: "SeatSathi",
    tagline: "Path to Pain-Free Driving",
    navHome: "Home",
    navRisk: "Risk Check",
    navStretches: "Stretches",
    navHelp: "Find Help",
    navLog: "Daily Log",
    
    // Auth / Login Page
    loginWelcome: "Driver Sign In",
    loginIntro: "Verify your profile with a quick, secure code.",
    formName: "Your Full Name",
    formPhone: "Mobile Number",
    btnSendOtp: "Request 4-Digit OTP",
    demoBanner: "Demo Mode: Your OTP is {otp}",
    enterOtp: "Enter the 4-digit code sent to your phone",
    invalidOtp: "Incorrect OTP. Please check the code and try again.",
    btnVerify: "Verify & Enter",
    btnBackToSignup: "Change Name/Number",
    btnResend: "Resend OTP",
    btnResendTimer: "Resend in",
    errorEmptyName: "Please enter your name.",
    errorInvalidPhone: "Please enter a valid 10-digit mobile number.",

    // Home Page
    heroTitle: "Relief for India's Hardest Working Drivers",
    heroDesc: "India has over 1 crore auto-rickshaw and taxi drivers who spend 10–14 hours a day in a seated position with no ergonomic support, irregular meals, and no access to healthcare. SeatSathi is built specifically to address your back pain, spinal stiffness, and daily fatigue—designed to fit your busy driving schedules.",
    personalNoteTitle: "Why We Built SeatSathi",
    personalNoteText: "My father has driven an auto-rickshaw for over 20 years. I have seen him return home every evening with a stiff neck, lower back pain, and deep exhaustion, silently bearing the physical cost of keeping our city moving. There was no tool designed for his daily reality. SeatSathi exists to give drivers like him the quick, practical relief they deserve between rides.",
    statsSeatedHours: "10-14 Hrs",
    statsSeatedHoursSub: "Average Seated Time",
    statsDriverCount: "1 Crore+",
    statsDriverCountSub: "Drivers in India",
    statsPainRate: "70%+",
    statsPainRateSub: "Report Chronic Pain",
    statsNote: "*Data based on occupational health surveys of commercial drivers.",
    featuresTitle: "Take Control of Your Health Today",
    ctaRiskCheck: "Check Pain Risk",
    ctaRiskCheckDesc: "Answer 5 quick questions to understand your body's stress level.",
    ctaStretches: "2-Min Stretches",
    ctaStretchesDesc: "Simple exercises you can do right inside your vehicle.",
    ctaFindHelp: "Find Nearby Clinics",
    ctaFindHelpDesc: "Locate free health camps and low-cost clinics near you.",
    ctaDailyLog: "Log Daily Pain",
    ctaDailyLogDesc: "Track your driving hours, sleep, and pain levels over time.",
    
    // Risk Check Page
    riskTitle: "Pain Risk Assessment",
    riskIntro: "Answer these 5 questions honestly to check if your body is at risk of chronic damage. It takes less than a minute.",
    q1: "How many hours did you drive today?",
    q2: "Where do you feel pain the most?",
    q3: "How often do you feel this pain?",
    q4: "How many hours of sleep did you get last night?",
    q5: "How often do you step out of the vehicle to stretch?",
    btnNext: "Next Question",
    btnPrev: "Back",
    btnSubmit: "Submit & Calculate Risk",
    resultTitle: "Your Health Risk Level",
    riskLow: "Low Risk",
    riskMod: "Moderate Risk",
    riskHigh: "High Risk",
    riskLowDesc: "Your daily driving habits look balanced. Keep up the good work and remember to stretch occasionally to prevent future pain.",
    riskModDesc: "Your body is showing signs of stress. Driving long hours with limited breaks is causing muscle fatigue. We recommend starting daily vehicle stretches.",
    riskHighDesc: "WARNING: Your body is under severe strain from long seated hours and frequent pain. Continued neglect can lead to chronic spinal damage. Please review our stretches and visit a clinic.",
    ctaGoToStretches: "Start Seated Stretches",
    ctaRecheck: "Start Over",

    // Stretches Page
    stretchesTitle: "Seated Relief Stretches",
    stretchesSubtitle: "Quick 2-minute stretches you can perform while waiting for a passenger or at a red light. Select a body part to filter:",
    filterAll: "All Stretches",
    filterNeck: "Neck",
    filterBack: "Back",
    filterShoulders: "Shoulders",
    filterLegs: "Legs & Feet",
    btnStartTimer: "Start 30s Timer",
    btnPause: "Pause",
    btnReset: "Reset",
    timerSec: "seconds remaining",
    stretchComplete: "Good job! Muscle tension released.",

    // Stretches Translation Dictionary
    stretch_neck_title: "Neck Tilts & Rolls",
    stretch_neck_step1: "Sit straight, let your shoulders drop naturally.",
    stretch_neck_step2: "Slowly tip your right ear towards your right shoulder until you feel a gentle stretch. Hold for 5 seconds.",
    stretch_neck_step3: "Roll your head forward slowly, bringing chin to chest.",
    stretch_neck_step4: "Slowly tilt left ear to left shoulder. Hold for 5 seconds. Repeat in reverse direction.",

    stretch_back_title: "Seated Spinal Twist",
    stretch_back_step1: "Sit forward in your seat with feet flat on the cabin floor.",
    stretch_back_step2: "Place your right hand on your left knee and your left hand on the seat backrest or armrest behind you.",
    stretch_back_step3: "Breathe in, then breathe out and gently twist your torso to the left, looking over your shoulder.",
    stretch_back_step4: "Hold for 10-15 seconds. Slowly release and repeat on the other side.",

    stretch_shoulders_title: "Shoulder Shrugs & Rolls",
    stretch_shoulders_step1: "Inhale deeply and shrug your shoulders up high towards your ears.",
    stretch_shoulders_step2: "Hold the shrug tightly for 3 seconds.",
    stretch_shoulders_step3: "Exhale and drop your shoulders down, rolling them backwards in a slow circular motion.",
    stretch_shoulders_step4: "Repeat this circular movement forward and backward 5 times.",

    stretch_chest_title: "Steering Wheel Chest Opener",
    stretch_chest_step1: "Place both hands on the steering wheel/handlebars at 9 and 3 o’clock positions.",
    stretch_chest_step2: "Push your chest forward and pull your shoulder blades together behind you.",
    stretch_chest_step3: "Gently tilt your chin upward slightly to expand your throat and chest.",
    stretch_chest_step4: "Hold for 15 seconds, breathing deeply and letting tension leave your chest muscles.",

    stretch_legs_title: "Ankle Pumps & Circles",
    stretch_legs_step1: "Lift your right foot slightly off the cabin floor.",
    stretch_legs_step2: "Point your toes forward away from you, then flex them upward towards your face. Do this 10 times.",
    stretch_legs_step3: "Rotate your ankle in a circle clockwise 5 times, then counter-clockwise 5 times.",
    stretch_legs_step4: "Lower your foot and repeat the sequence with your left foot.",

    stretch_wrist_title: "Wrist & Finger Stretches",
    stretch_wrist_step1: "Extend your right arm straight in front of you, palm facing outward, fingers pointing up.",
    stretch_wrist_step2: "Use your left hand to pull your fingers gently back towards your body until you stretch the forearm.",
    stretch_wrist_step3: "Hold for 10 seconds, then point your fingers down and stretch the top of your wrist.",
    stretch_wrist_step4: "Repeat the cycle with your left arm and fingers.",

    // Find Help Page
    helpTitle: "Nearby Clinics & Health Camps",
    helpSubtitle: "Find free or low-cost medical camps and government clinics set up specifically for transit workers and drivers.",
    helpNote: "Note: In the full version, this page will use your phone's GPS to find live local clinics. Below is an illustrative list of local clinics and camps near your current location.",
    clinicFilterAll: "All Resources",
    clinicFilterCamp: "Free Camps",
    clinicFilterGov: "Government Centers",
    clinicFilterPhysio: "Physiotherapists",
    freeTag: "FREE",
    lowCostTag: "LOW-COST",
    btnGetDirections: "Show Directions",
    btnCall: "Call Clinic",

    // Daily Log Page
    logTitle: "Daily Driver Log",
    logSubtitle: "Turn your daily exhaustion into visible data. Keep tracking to see if taking regular breaks helps reduce your pain.",
    formDate: "Date",
    formHours: "Hours Driven Today",
    formSleep: "Sleep Last Night (Hours)",
    formPain: "Pain Level (1 = No Pain, 10 = Severe Pain)",
    formEarnings: "Earnings Today (Optional - ₹)",
    btnSaveLog: "Save Log Entry",
    logSuccess: "Log saved successfully!",
    chartTitle: "Your Pain vs. Driving Hours Trend",
    chartSubtitle: "Visualizing the relationship between your work hours and physical strain",
    noLogsYet: "No log entries found. Start by entering today's details above!",
    painLabel: "Pain Level (1-10)",
    hoursLabel: "Hours Driven",
    streakCount: "Active Log Streak",
    streakDays: "days in a row"
  },
  hi: {
    appName: "सीटसाथी",
    tagline: "दर्द-मुक्त ड्राइविंग का रास्ता",
    navHome: "होम",
    navRisk: "जोखिम जांच",
    navStretches: "स्ट्रेच व्यायाम",
    navHelp: "नज़दीकी मदद",
    navLog: "दैनिक लॉग",
    
    // Auth / Login Page
    loginWelcome: "ड्राइवर लॉगिन",
    loginIntro: "त्वरित और सुरक्षित कोड के साथ अपनी प्रोफाइल सत्यापित करें।",
    formName: "आपका पूरा नाम",
    formPhone: "मोबाइल नंबर",
    btnSendOtp: "4-अंकीय ओटीपी प्राप्त करें",
    demoBanner: "डेमो मोड: आपका ओटीपी {otp} है",
    enterOtp: "अपने फोन पर भेजा गया 4-अंकीय कोड दर्ज करें",
    invalidOtp: "गलत ओटीपी। कृपया कोड जांचें और पुनः प्रयास करें।",
    btnVerify: "सत्यापित करें और प्रवेश करें",
    btnBackToSignup: "नाम/नंबर बदलें",
    btnResend: "ओटीपी दोबारा भेजें",
    btnResendTimer: "पुनः भेजें",
    errorEmptyName: "कृपया अपना नाम दर्ज करें।",
    errorInvalidPhone: "कृपया एक वैध 10-अंकीय मोबाइल नंबर दर्ज करें।",

    // Home Page
    heroTitle: "भारत के सबसे मेहनती ड्राइवरों के लिए राहत",
    heroDesc: "भारत में 1 करोड़ से अधिक ऑटो-रिक्शा और टैक्सी चालक हैं जो बिना किसी एर्गोनोमिक सहायता, अनियमित भोजन समय और स्वास्थ्य सेवा तक पहुंच के बिना दिन में 10-14 घंटे बैठे रहते हैं। सीटसाथी को विशेष रूप से आपके पीठ दर्द, रीढ़ की अकड़न और दैनिक थकान को दूर करने के लिए बनाया गया है—जो आपके व्यस्त ड्राइविंग शेड्यूल में फिट बैठता है।",
    personalNoteTitle: "हमने सीटसाथी क्यों बनाया",
    personalNoteText: "मेरे पिता ने 20 से अधिक वर्षों तक ऑटो-रिक्शा चलाया है। मैंने उन्हें हर शाम गर्दन में अकड़न, पीठ के निचले हिस्से में दर्द और गहरी थकावट के साथ घर लौटते देखा है, जो हमारे शहर को चलते रखने की शारीरिक कीमत को चुपचाप सहते हैं। उनकी दैनिक वास्तविकता के लिए कोई डिजिटल साधन नहीं था। सीटसाथी का अस्तित्व उनके जैसे ड्राइवरों को सवारी मिलने के बीच त्वरित, व्यावहारिक राहत देने के लिए है।",
    statsSeatedHours: "10-14 घंटे",
    statsSeatedHoursSub: "औसत बैठने का समय",
    statsDriverCount: "1 करोड़+",
    statsDriverCountSub: "भारत में चालक",
    statsPainRate: "70%+",
    statsPainRateSub: "क्रोनिक दर्द की रिपोर्ट",
    statsNote: "*वाणिज्यिक ड्राइवरों के व्यावसायिक स्वास्थ्य सर्वेक्षणों पर आधारित डेटा।",
    featuresTitle: "आज ही अपने स्वास्थ्य की जिम्मेदारी लें",
    ctaRiskCheck: "दर्द के जोखिम की जांच करें",
    ctaRiskCheckDesc: "अपने शरीर के तनाव के स्तर को समझने के लिए 5 त्वरित प्रश्नों के उत्तर दें।",
    ctaStretches: "2-मिनट के स्ट्रेच",
    ctaStretchesDesc: "सरल व्यायाम जो आप सीधे अपने वाहन के अंदर कर सकते हैं।",
    ctaFindHelp: "नज़दीकी क्लीनिक खोजें",
    ctaFindHelpDesc: "अपने आस-पास मुफ्त स्वास्थ्य शिविरों और कम लागत वाले क्लीनिकों का पता लगाएं।",
    ctaDailyLog: "दैनिक दर्द लॉग करें",
    ctaDailyLogDesc: "समय के साथ अपने ड्राइविंग घंटे, नींद और दर्द के स्तर को ट्रैक करें।",
    
    // Risk Check Page
    riskTitle: "दर्द जोखिम मूल्यांकन",
    riskIntro: "यह जांचने के लिए कि क्या आपके शरीर को पुराने नुकसान का खतरा है, इन 5 प्रश्नों के ईमानदारी से उत्तर दें। इसमें एक मिनट से भी कम समय लगता है।",
    q1: "आज आपने कितने घंटे गाड़ी चलाई?",
    q2: "आपको सबसे अधिक दर्द कहाँ महसूस होता है?",
    q3: "आप यह दर्द कितनी बार महसूस करते हैं?",
    q4: "कल रात आपने कितने घंटे की नींद ली?",
    q5: "आप स्ट्रेचिंग के लिए वाहन से बाहर कितनी बार कदम रखते हैं?",
    btnNext: "अगला प्रश्न",
    btnPrev: "पीछे",
    btnSubmit: "सबमिट करें और जोखिम जानें",
    resultTitle: "आपका स्वास्थ्य जोखिम स्तर",
    riskLow: "कम जोखिम",
    riskMod: "मध्यम जोखिम",
    riskHigh: "उच्च जोखिम",
    riskLowDesc: "आपकी दैनिक ड्राइविंग आदतें संतुलित दिखती हैं। अच्छा काम जारी रखें और भविष्य के दर्द को रोकने के लिए कभीकभार स्ट्रेच करना याद रखें।",
    riskModDesc: "आपका शरीर तनाव के संकेत दे रहा है। सीमित ब्रेक के साथ लंबे समय तक गाड़ी चलाने से मांसपेशियों में थकान हो रही है। हम दैनिक वाहन स्ट्रेच शुरू करने की सलाह देते हैं।",
    riskHighDesc: "चेतावनी: लंबे समय तक बैठने और बार-बार होने वाले दर्द के कारण आपका शरीर गंभीर तनाव में है। लगातार उपेक्षा करने से रीढ़ की हड्डी को स्थायी नुकसान हो सकता है। कृपया हमारे स्ट्रेच व्यायाम देखें और डॉक्टर से मिलें।",
    ctaGoToStretches: "वाहन में स्ट्रेचिंग शुरू करें",
    ctaRecheck: "फिर से शुरू करें",

    // Stretches Page
    stretchesTitle: "बैठकर राहत देने वाले स्ट्रेच",
    stretchesSubtitle: "त्वरित 2-मिनट के व्यायाम जो आप सवारी का इंतज़ार करते समय या लाल बत्ती पर कर सकते हैं। फ़िल्टर करने के लिए शरीर का अंग चुनें:",
    filterAll: "सभी व्यायाम",
    filterNeck: "गर्दन",
    filterBack: "पीठ",
    filterShoulders: "कंधे",
    filterLegs: "पैर और पंजे",
    btnStartTimer: "30 सेकेण्ड टाइमर शुरू करें",
    btnPause: "रोकें",
    btnReset: "रिसेट करें",
    timerSec: "सेकंड बचे हैं",
    stretchComplete: "बहुत बढ़िया! मांसपेशियों का तनाव कम हुआ।",

    // Stretches Translation Dictionary (Hindi)
    stretch_neck_title: "गर्दन झुकाना और घुमाना",
    stretch_neck_step1: "सीधे बैठें, अपने कंधों को स्वाभाविक रूप से ढीला छोड़ें।",
    stretch_neck_step2: "धीरे-धीरे अपने दाहिने कान को अपने दाहिने कंधे की ओर झुकाएं जब तक कि खिंचाव महसूस न हो। 5 सेकंड तक रुकें।",
    stretch_neck_step3: "सिर को धीरे-धीरे आगे की ओर घुमाते हुए ठुड्डी को छाती से लगाएं।",
    stretch_neck_step4: "धीरे-धीरे बाएं कान को बाएं कंधे की ओर झुकाएं। 5 सेकंड तक रुकें। विपरीत दिशा में दोहराएं।",

    stretch_back_title: "बैठकर रीढ़ की घुमावदार स्ट्रेच",
    stretch_back_step1: "कैबिन के फर्श पर पैर सपाट रखकर अपनी सीट पर आगे बैठें।",
    stretch_back_step2: "अपना दाहिना हाथ अपने बाएं घुटने पर और बायां हाथ अपने पीछे सीट के बैकरेस्ट पर रखें।",
    stretch_back_step3: "सांस लें, फिर सांस छोड़ें और अपने धड़ को धीरे से बाईं ओर घुमाएं, कंधे के ऊपर से देखें।",
    stretch_back_step4: "10-15 सेकंड तक रुकें। धीरे से छोड़ें और दूसरी तरफ दोहराएं।",

    stretch_shoulders_title: "कंधे सिकुड़ना और घुमाना",
    stretch_shoulders_step1: "गहरी सांस लें और अपने कंधों को अपने कानों की तरफ ऊंचा सिकोड़ें।",
    stretch_shoulders_step2: "सिकुड़े हुए कंधों को 3 सेकंड के लिए कसकर रखें।",
    stretch_shoulders_step3: "सांस छोड़ें और अपने कंधों को नीचे गिराते हुए धीरे-धीरे गोलाकार गति में पीछे की ओर घुमाएं।",
    stretch_shoulders_step4: "इस गोलाकार आंदोलन को आगे और पीछे 5 बार दोहराएं।",

    stretch_chest_title: "स्टीयरिंग व्हील चेस्ट ओपनर",
    stretch_chest_step1: "दोनों हाथों को स्टीयरिंग व्हील पर 9 और 3 बजे की स्थिति में रखें।",
    stretch_chest_step2: "अपनी छाती को आगे बढ़ाएं और अपने कंधे के ब्लेड को अपने पीछे एक साथ खींचें।",
    stretch_chest_step3: "गले और छाती को फैलाने के लिए धीरे-धीरे अपनी ठुड्डी को थोड़ा ऊपर की ओर झुकाएं।",
    stretch_chest_step4: "गहरी सांस लेते हुए 15 सेकंड तक रुकें और छाती की मांसपेशियों को तनाव मुक्त होने दें।",

    stretch_legs_title: "टखने का पंप और घुमाव",
    stretch_legs_step1: "अपने दाहिने पैर को कैबिन के फर्श से थोड़ा ऊपर उठाएं।",
    stretch_legs_step2: "अपने पंजों को अपने से दूर आगे की ओर इंगित करें, फिर उन्हें अपने चेहरे की ओर ऊपर की ओर मोड़ें। ऐसा 10 बार करें।",
    stretch_legs_step3: "अपने टखने को दक्षिणावर्त 5 बार और फिर वामावर्त 5 बार घुमाएं।",
    stretch_legs_step4: "अपने पैर को नीचे करें और बाएं पैर के साथ यही प्रक्रिया दोहराएं।",

    stretch_wrist_title: "कलाई और उंगलियों का खिंचाव",
    stretch_wrist_step1: "अपने दाहिने हाथ को सीधे अपने सामने फैलाएं, हथेली बाहर की ओर हो, उंगलियां ऊपर की ओर हों।",
    stretch_wrist_step2: "बाएं हाथ से उंगलियों को धीरे-धीरे पीछे की ओर खींचें जब तक कि अग्रबाहु में खिंचाव महसूस न हो।",
    stretch_wrist_step3: "10 सेकंड तक रुकें, फिर उंगलियों को नीचे की ओर इंगित करें और कलाई के ऊपरी हिस्से को स्ट्रेच करें।",
    stretch_wrist_step4: "अपने बाएं हाथ और उंगलियों के साथ इस प्रक्रिया को दोहराएं।",

    // Find Help Page
    helpTitle: "नज़दीकी क्लीनिक और स्वास्थ्य शिविर",
    helpSubtitle: "पारगमन कर्मचारियों और ड्राइवरों के लिए विशेष रूप से स्थापित मुफ्त या कम लागत वाले चिकित्सा शिविर और सरकारी क्लीनिक खोजें।",
    helpNote: "नोट: पूर्ण संस्करण में, यह पृष्ठ लाइव स्थानीय क्लीनिकों को खोजने के लिए आपके फ़ोन के जीपीएस का उपयोग करेगा। नीचे आपके वर्तमान स्थान के पास के क्लीनिकों और शिविरों की एक उदाहरण सूची है।",
    clinicFilterAll: "सभी संसाधन",
    clinicFilterCamp: "मुफ्त शिविर",
    clinicFilterGov: "सरकारी केंद्र",
    clinicFilterPhysio: "फिजियोथेरेपिस्ट",
    freeTag: "मुफ्त",
    lowCostTag: "कम लागत",
    btnGetDirections: "दिशा निर्देश देखें",
    btnCall: "कॉल करें",

    // Daily Log Page
    logTitle: "दैनिक चालक लॉग",
    logSubtitle: "अपनी दैनिक थकावट को दृश्य डेटा में बदलें। यह देखने के लिए ट्रैक करते रहें कि क्या नियमित ब्रेक लेने से आपका दर्द कम होता है।",
    formDate: "तारीख",
    formHours: "आज चलाई गई अवधि (घंटे)",
    formSleep: "कल रात की नींद (घंटे)",
    formPain: "दर्द का स्तर (1 = कोई दर्द नहीं, 10 = बहुत तेज़ दर्द)",
    formEarnings: "आज की कमाई (वैकल्पिक - ₹)",
    btnSaveLog: "लॉग सुरक्षित करें",
    logSuccess: "लॉग सफलतापूर्वक सुरक्षित किया गया!",
    chartTitle: "आपका दर्द बनाम ड्राइविंग समय",
    chartSubtitle: "आपके काम के घंटे और शारीरिक तनाव के बीच संबंध को दर्शाना",
    noLogsYet: "कोई लॉग प्रविष्टि नहीं मिली। ऊपर आज का विवरण दर्ज करके शुरू करें!",
    painLabel: "दर्द का स्तर (1-10)",
    hoursLabel: "चलाए गए घंटे",
    streakCount: "सक्रिय लॉग लकीर (स्ट्रैक)",
    streakDays: "लगातार दिन"
  },
  mr: {
    appName: "सीटसाथी",
    tagline: "दुखापतीशिवाय ड्रायव्हिंगचा मार्ग",
    navHome: "होम",
    navRisk: "त्रास तपासणी",
    navStretches: "स्ट्रेच व्यायाम",
    navHelp: "नजीकची मदत",
    navLog: "दैनिक नोंद",
    
    // Auth / Login Page
    loginWelcome: "ड्रायव्हर लॉगिन",
    loginIntro: "सोप्या आणि सुरक्षित कोडने तुमची प्रोफाईल सुरू करा.",
    formName: "तुमचे पूर्ण नाव",
    formPhone: "मोबाईल नंबर",
    btnSendOtp: "४-अंकी ओटीपी मागवा",
    demoBanner: "डेमो मोड: तुमचा ओटीपी {otp} आहे",
    enterOtp: "तुमच्या phoneवर आलेला ४-अंकी कोड टाका",
    invalidOtp: "चुकीचा ओटीपी. कृपया कोड तपासून पुन्हा प्रयत्न करा.",
    btnVerify: "तपासा आणि सुरू करा",
    btnBackToSignup: "नाव/नंबर बदला",
    btnResend: "ओटीपी पुन्हा पाठवा",
    btnResendTimer: "पुन्हा पाठवा",
    errorEmptyName: "कृपया तुमचे नाव टाका.",
    errorInvalidPhone: "कृपया योग्य १०-अंकी मोबाईल नंबर टाका.",

    // Home Page
    heroTitle: "भारतातील सर्वात कष्टाळू ड्रायव्हर्ससाठी आराम",
    heroDesc: "भारतात १ कोटीहून अधिक ऑटो-रिक्षा आणि टॅक्सी चालक आहेत जे कोणत्याही एर्गोनॉमिक मदतीशिवाय, जेवणाच्या अनिश्चित वेळा आणि आरोग्याची कोणतीही सुविधा नसताना दिवसातून १०-१४ तास बसून राहतात. सीटसाथी हे विशेषतः तुमच्या पाठीचे दुखणे, मानेची अकडण आणि रोजचा थकवा दूर करण्यासाठी बनवले आहे—जे तुमच्या व्यस्त ड्रायव्हिंग वेळेत सहज बसेल.",
    personalNoteTitle: "आम्ही सीटसाथी का बनवले",
    personalNoteText: "माझ्या वडिलांनी २० वर्षांहून अधिक काळ ऑटो-रिक्षा चालवली आहे. मी त्यांना रोज संध्याकाळी मानदुखी, पाठदुखी आणि प्रचंड थकव्याने घरी परतताना पाहिले आहे. ते आपल्या शहराला चालवण्यासाठी शरीराचा होणारा त्रास गपचूप सहन करतात. त्यांच्या दैनंदिन वास्तवासाठी कोणतेही साधन नव्हते. सीटसाथीचा उद्देश त्यांच्यासारख्या ड्रायव्हर्सना भाड्याच्या मधल्या वेळेत झटपट, सोपा आराम देण्याचा आहे.",
    statsSeatedHours: "10-14 तास",
    statsSeatedHoursSub: "सरासरी बसण्याचा वेळ",
    statsDriverCount: "1 कोटी+",
    statsDriverCountSub: "भारतातील चालक",
    statsPainRate: "70%+",
    statsPainRateSub: "तीव्र त्रासाची नोंद",
    statsNote: "*चालकांच्या आरोग्याबाबत केलेल्या सर्वेक्षणावर आधारित माहिती.",
    featuresTitle: "आजच स्वतःच्या आरोग्याची काळजी घ्या",
    ctaRiskCheck: "त्रासाच्या जोखमीची तपासणी",
    ctaRiskCheckDesc: "तुमच्या शरीराचा थकवा समजून घेण्यासाठी ५ सोप्या प्रश्नांची उत्तरे द्या.",
    ctaStretches: "२-मिनिटांचे स्ट्रेचेस",
    ctaStretchesDesc: "सोपे व्यायाम जे तुम्ही थेट गाडीत बसून करू शकता.",
    ctaFindHelp: "नजीकचे दवाखाने शोधा",
    ctaFindHelpDesc: "तुमच्या जवळचे मोफत आरोग्य शिबिर आणि स्वस्त दवाखाने शोधा.",
    ctaDailyLog: "रोजच्या त्रासाची नोंद",
    ctaDailyLogDesc: "तुमचे कामाचे तास, झोप आणि होणारा त्रास नियमितपणे ट्रॅक करा.",
    
    // Risk Check Page
    riskTitle: "शारीरिक त्रासाची तपासणी",
    riskIntro: "तुमच्या शरीराला भविष्यात गंभीर धोका टाळण्यासाठी या ५ प्रश्नांची उत्तरे प्रामाणिकपणे द्या. एक मिनिटापेक्षा कमी वेळ लागेल.",
    q1: "आज तुम्ही किती तास गाडी चालवली?",
    q2: "तुम्हाला सर्वात जास्त त्रास कुठे होतो?",
    q3: "हा त्रास तुम्हाला किती वेळा जाणवतो?",
    q4: "काल रात्री तुम्हाला किती तास झोप मिळाली?",
    q5: "व्यायाम करण्यासाठी तुम्ही गाडीतून बाहेर किती वेळा उतरता?",
    btnNext: "पुढील प्रश्न",
    btnPrev: "मागे",
    btnSubmit: "सबमिट करा आणि धोका तपासा",
    resultTitle: "तुमची जोखीम पातळी",
    riskLow: "कमी जोखीम",
    riskMod: "मध्यम जोखीम",
    riskHigh: "उच्च जोखीम",
    riskLowDesc: "तुमच्या गाडी चालवण्याच्या सवयी चांगल्या आहेत. भविष्यातील त्रास टाळण्यासाठी कधीकधी शरीर थोडे स्ट्रेच करा.",
    riskModDesc: "तुमचे शरीर थकले आहे. न थांबता सतत ड्रायव्हिंग केल्यामुळे स्नायूंवर ताण येतोय. तुम्ही रोज थोडे स्ट्रेच व्यायाम सुरू करावेत.",
    riskHighDesc: "चेतावनी: सततचे जास्त तास बसणे आणि वारंवार होणाऱ्या त्रासामुळे तुमच्या शरीरावर गंभीर ताण येत आहे. याकडे दुर्लक्ष केल्यास पाठीचा गंभीर आजार होऊ शकतो. कृपया आमचे व्यायाम करा आणि डॉक्टरांना दाखवा.",
    ctaGoToStretches: "गाडीत व्यायाम सुरू करा",
    ctaRecheck: "पुन्हा सुरू करा",

    // Stretches Page
    stretchesTitle: "बसून करायचे सोपे व्यायाम",
    stretchesSubtitle: "प्रवाशाची वाट पाहत असताना किंवा ट्रॅफिक सिग्नलवर २ मिनिटात करता येतील असे सोपे व्यायाम. खालील अवयव निवडून व्यायाम शोधा:",
    filterAll: "सर्व व्यायाम",
    filterNeck: "मान",
    filterBack: "पाठ",
    filterShoulders: "खांदे",
    filterLegs: "पाय आणि पावले",
    btnStartTimer: "३० सेकंद टाईमर सुरू करा",
    btnPause: "थांबवा",
    btnReset: "रिसेट",
    timerSec: "सेकंद शिल्लक",
    stretchComplete: "उत्कृष्ट! स्नायूंचा ताण कमी झाला आहे.",

    // Stretches Translation Dictionary (Marathi)
    stretch_neck_title: "मानेचे व्यायाम (Neck Tilts & Rolls)",
    stretch_neck_step1: "ताठ बसा आणि खांदे मोकळे सोडा.",
    stretch_neck_step2: "हळूहळू उजवा कान उजव्या खांद्याकडे झुकवा, हलका ताण जाणवेपर्यंत ५ सेकंद थांबा.",
    stretch_neck_step3: "डोके हळूहळू समोरून फिरवत हनुवटी छातीला लावा.",
    stretch_neck_step4: "हळूहळू डावा कान डाव्या खांद्याकडे झुकवा. ५ सेकंद थांबा. विरुद्ध दिशेने पुन्हा करा.",

    stretch_back_title: "पाठीचा फिरता व्यायाम (Seated Spinal Twist)",
    stretch_back_step1: "गाडीच्या फरशीवर पाय सपाट ठेवून सीटवर थोडे पुढे बसा.",
    stretch_back_step2: "उजवा हात डाव्या गुडघ्यावर आणि डावा हात तुमच्या पाठीमागे सीटवर ठेवा.",
    stretch_back_step3: "श्वास घ्या, श्वास सोडताना आपले शरीर हळूहळू डावीकडे फिरवून खांद्यावरून मागे बघा.",
    stretch_back_step4: "१०-१५ सेकंद थांबा. हळूच सरळ व्हा आणि दुसऱ्या बाजूने पुन्हा करा.",

    stretch_shoulders_title: "खांदे वर-खाली करणे आणि फिरवणे (Shoulder Shrugs & Rolls)",
    stretch_shoulders_step1: "दीर्घ श्वास घ्या आणि खांदे कानांच्या दिशेने वर उचला.",
    stretch_shoulders_step2: "खांदे ३ सेकंदांसाठी तसेच वर ताणून ठेवा.",
    stretch_shoulders_step3: "श्वास सोडत खांदे खाली आणा आणि वर्तुळाकार आकारात मागे फिरवा.",
    stretch_shoulders_step4: "अशी वर्तुळाकार हालचाल पुढे आणि मागे ५ वेळा करा.",

    stretch_chest_title: "स्टीयरिंग व्हील छातीचा व्यायाम (Steering Wheel Chest Opener)",
    stretch_chest_step1: "दोन्ही हात स्टीयरिंग व्हीलवर ९ आणि ३ च्या जागी ठेवा.",
    stretch_chest_step2: "छाती पुढे काढा आणि खांद्याची हाडे पाठीमागे एकत्र खेचा.",
    stretch_chest_step3: "हनुवटी हळूच वर करून छाती आणि गळा मोकळा करा.",
    stretch_chest_step4: "दीर्घ श्वास घेत १५ सेकंद थांबा, छातीचे स्नायू सैल सोडा.",

    stretch_legs_title: "पावलांचे पंप आणि गोल फिरवणे (Ankle Pumps & Circles)",
    stretch_legs_step1: "उजवा पाय गाडीच्या फरशीपासून थोडा वर उचला.",
    stretch_legs_step2: "पावलाची बोटे समोरच्या बाजूला ताणा, नंतर चेहऱ्याच्या दिशेने मागे खेचा. असे १० वेळा करा.",
    stretch_legs_step3: "पाऊल गोलाकार घड्याळाच्या दिशेने ५ वेळा आणि उलट दिशेने ५ वेळा फिरवा.",
    stretch_legs_step4: "पाय खाली ठेवा आणि डाव्या पायाने हीच कृती पुन्हा करा.",

    stretch_wrist_title: "कलाई आणि बोटांचे स्ट्रेचेस (Wrist & Finger Stretches)",
    stretch_wrist_step1: "उजवा हात समोर सरळ ठेवा, पंजा बाहेरच्या बाजूला आणि बोटे वरच्या दिशेने करा.",
    stretch_wrist_step2: "डाव्या हाताने उजव्या हाताची बोटे मागे ओढा जोपर्यंत हाताला हलका ताण जाणवत नाही.",
    stretch_wrist_step3: "१० सेकंद थांबा, नंतर बोटे खाली करा आणि मनगटाच्या वरच्या भागाला ताण द्या.",
    stretch_wrist_step4: "डाव्या हाताने आणि बोटांनी हीच कृती पुन्हा करा.",

    // Find Help Page
    helpTitle: "नजीकचे दवाखाने आणि आरोग्य शिबिर",
    helpSubtitle: "ड्रायव्हर्ससाठी विशेषतः सुरू केलेले मोफत किंवा स्वस्त आरोग्य शिबिर आणि सरकारी दवाखाने शोधा.",
    helpNote: "टीप: पूर्ण ॲपमध्ये हे पेज मोबाईलच्या जीपीएसचा वापर करून जवळचे दवाखाने दाखवेल. खाली सध्या तुमच्या जवळ असणाऱ्या दवाखान्यांची नमुना यादी दिली आहे.",
    clinicFilterAll: "सर्व सोयी",
    clinicFilterCamp: "मोफत शिबिर",
    clinicFilterGov: "सरकारी केंद्र",
    clinicFilterPhysio: "फिजियोथेरेपिस्ट",
    freeTag: "मोफत",
    lowCostTag: "स्वस्त",
    btnGetDirections: "रस्ता दाखवा",
    btnCall: "फोन करा",

    // Daily Log Page
    logTitle: "दैनंदिन ड्रायव्हर डायरी",
    logSubtitle: "तुमचा रोजचा थकवा डेटाच्या रूपात पहा. नियमित विश्रांती घेतल्याने तुमचा शारीरिक त्रास खरोखर कमी होतो का ते तपासा.",
    formDate: "तारीख",
    formHours: "आज किती तास गाडी चालवली",
    formSleep: "काल रात्रीची झोप (तास)",
    formPain: "त्रासाची पातळी (१ = काहीच नाही, १० = खूप तीव्र त्रास)",
    formEarnings: "आजची कमाई (वैकल्पिक - ₹)",
    btnSaveLog: "नोंद जतन करा",
    logSuccess: "माहिती यशस्वीरीत्या जतन केली!",
    chartTitle: "तुमचा त्रास विरुद्ध कामाचे तास",
    chartSubtitle: "तुमच्या कामाचे तास आणि शरीराचा थकवा यांच्यातील परस्पर संबंध",
    noLogsYet: "अजून कोणतीही नोंद केलेली नाही. वर आजची माहिती भरून सुरुवात करा!",
    painLabel: "त्रासाची पातळी (१-१०)",
    hoursLabel: "चालवलेले तास",
    streakCount: "नियमित नोंद दिवस",
    streakDays: "सलग दिवस"
  },
  te: {
    appName: "సీట్సాథి",
    tagline: "నొప్పి లేని డ్రైవింగ్ మార్గం",
    navHome: "హోమ్",
    navRisk: "నొప్పి ప్రమాదం",
    navStretches: "వ్యాయామాలు",
    navHelp: "సహాయ కేంద్రాలు",
    navLog: "రోజువారీ లాగ్",
    
    // Auth / Login Page
    loginWelcome: "డ్రైవర్ సైన్ ఇన్",
    loginIntro: "సురక్షితమైన కోడ్‌తో మీ ప్రొఫైల్‌ను వెంటనే వెరిఫై చేసుకోండి.",
    formName: "మీ పూర్తి పేరు",
    formPhone: "మొబైల్ నంబర్",
    btnSendOtp: "4-అంకెల OTP ని పంపండి",
    demoBanner: "డెమో మోడ్: మీ OTP {otp}",
    enterOtp: "మీ ఫోన్‌కు పంపిన 4-అంకెల కోడ్‌ను నమోదు చేయండి",
    invalidOtp: "తప్పు OTP. దయచేసి కోడ్‌ని తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.",
    btnVerify: "వెరిఫై చేసి లోపలికి వెళ్ళండి",
    btnBackToSignup: "పేరు/నంబర్ మార్చండి",
    btnResend: "OTP ని మళ్లీ పంపండి",
    btnResendTimer: "మళ్లీ పంపడానికి",
    errorEmptyName: "దయచేసి మీ పేరును నమోదు చేయండి.",
    errorInvalidPhone: "దయచేసి సరైన 10-అంకెల మొబైల్ నంబర్‌ను నమోదు చేయండి.",

    // Home Page
    heroTitle: "భారతదేశంలో అత్యంత కష్టపడి పనిచేసే డ్రైవర్లకు ఉపశమనం",
    heroDesc: "భారతదేశంలో కోటి మందికి పైగా ఆటో-రిక్షా, టాక్సీ డ్రైవర్లు ఉన్నారు. వీరు సరైన సీటింగ్ సపోర్ట్ లేకుండా, సరైన సమయానికి తిండి తినకుండా, వైద్య సదుపాయాలు లేకుండా రోజుకు 10-14 గంటలు కూర్చుని డ్రైవింగ్ చేస్తున్నారు. మీ నడుము నొప్పి, వెన్నునొప్పి మరియు రోజంతా ఉండే అలసటను తగ్గించడానికి సీట్సాథి సహాయపడుతుంది. ఇది మీ బిజీ సమయానికి సరిపోయేలా రూపొందించబడింది.",
    personalNoteTitle: "ఈ యాప్‌ను ఎందుకు తయారు చేసాము",
    personalNoteText: "మా నాన్నగారు 20 ఏళ్లకు పైగా ఆటో నడిపారు. ఆయన ప్రతిరోజూ సాయంత్రం మెడనొప్పి, నడుమునొప్పి మరియు తీవ్రమైన అలసటతో ఇంటికి రావడం నేను చూశాను. నగరం కోసం ఆయన కష్టపడే శారీరక శ్రమకు విలువ లేదు. ఆయనలాంటి డ్రైవర్లకు ప్యాసింజర్స్ కోసం ఎదురుచూసే ఖాళీ సమయంలో త్వరగా ఉపశమనం కలిగించడం కోసమే సీట్సాథి తయారు చేయబడింది.",
    statsSeatedHours: "10-14 గంటలు",
    statsSeatedHoursSub: "సగటు సీటింగ్ సమయం",
    statsDriverCount: "1 కోటికి పైగా",
    statsDriverCountSub: "భారతదేశంలో డ్రైవర్లు",
    statsPainRate: "70% కి పైగా",
    statsPainRateSub: "నొప్పితో బాధపడుతున్నవారు",
    statsNote: "*డ్రైవర్ల ఆరోగ్య సర్వేల ఆధారంగా సేకరించిన సమాచారం.",
    featuresTitle: "ఈరోజే మీ ఆరోగ్యంపై శ్రద్ధ పెట్టండి",
    ctaRiskCheck: "నొప్పి రిస్క్ టెస్ట్",
    ctaRiskCheckDesc: "మీ శరీర అలసట స్థాయిని తెలుసుకోవడానికి 5 చిన్న ప్రశ్నలకు సమాధానాలు ఇవ్వండి.",
    ctaStretches: "2 నిమిషాల వ్యాయామం",
    ctaStretchesDesc: "మీ వాహనంలోనే సులభంగా చేయగలిగే వ్యాయామాలు.",
    ctaFindHelp: "సమీప క్లినిక్‌లు",
    ctaFindHelpDesc: "మీకు దగ్గరలో ఉన్న ఉచిత హెల్త్ క్యాంపులు మరియు తక్కువ ఖర్చుతో కూడిన క్లినిక్‌లను కనుగొనండి.",
    ctaDailyLog: "రోజువారీ నొప్పి రికార్డు",
    ctaDailyLogDesc: "మీ డ్రైవింగ్ గంటలు, నిద్ర మరియు నొప్పిని ప్రతిరోజూ నమోదు చేసుకోండి.",
    
    // Risk Check Page
    riskTitle: "నొప్పి ప్రమాద అంచనా",
    riskIntro: "మీ వెన్నెముకకు ఏదైనా ప్రమాదం ఉందేమో తెలుసుకోవడానికి ఈ 5 ప్రశ్నలకు నిజాయితీగా సమాధానం ఇవ్వండి. దీనికి నిమిషం కంటే తక్కువ సమయం పడుతుంది.",
    q1: "ఈరోజు మీరు ఎన్ని గంటలు బండి నడిపారు?",
    q2: "మీకు ఎక్కువగా ఎక్కడ నొప్పిగా ఉంటుంది?",
    q3: "ఈ నొప్పి మీకు ఎంత తరచుగా వస్తుంది?",
    q4: "గత రాత్రి మీరు ఎన్ని గంటలు నిద్రపోయారు?",
    q5: "వ్యాయామం చేయడానికి మీరు బండి దిగి ఎంత తరచుగా నడుస్తారు?",
    btnNext: "తదుపరి ప్రశ్న",
    btnPrev: "వెనుకకు",
    btnSubmit: "సమర్పించి రిస్క్ తెలుసుకోండి",
    resultTitle: "మీ ఆరోగ్య ప్రమాద స్థాయి",
    riskLow: "తక్కువ ప్రమాదం",
    riskMod: "మధ్యస్థ ప్రమాదం",
    riskHigh: "ఎక్కువ ప్రమాదం",
    riskLowDesc: "మీ డ్రైవింగ్ అలవాట్లు బాగున్నాయి. భవిష్యత్తులో నొప్పి రాకుండా ఉండటానికి అప్పుడప్పుడు కొద్దిగా వ్యాయామం చేయండి.",
    riskModDesc: "మీ శరీరం అలసటకు గురవుతోంది. విశ్రాంతి లేకుండా ఎక్కువ సమయం డ్రైవింగ్ చేయడం వల్ల కండరాలు అలసిపోతాయి. రోజువారీ వ్యాయామాలు ప్రారంభించండి.",
    riskHighDesc: "హెచ్చరిక: ఎక్కువ గంటలు కూర్చోవడం మరియు తరచుగా వస్తున్న నొప్పి వల్ల మీ శరీరం తీవ్రమైన ఒత్తిడిలో ఉంది. దీనిని నిర్లక్ష్యం చేస్తే వెన్నుముక శాశ్వతంగా దెబ్బతింటుంది. దయచేసి వ్యాయామాలు చేసి వెంటనే డాక్టర్‌ను సంప్రదించండి.",
    ctaGoToStretches: "వాహనంలోనే వ్యాయామం ప్రారంభించండి",
    ctaRecheck: "మళ్ళీ మొదలుపెట్టండి",

    // Stretches Page
    stretchesTitle: "కూర్చుని చేసే వ్యాయామాలు",
    stretchesSubtitle: "ట్రాఫిక్ సిగ్నల్ దగ్గర లేదా ప్యాసింజర్ కోసం ఎదురుచూసే 2 నిమిషాల్లో చేసుకోగలిగే వ్యాయామాలు. నొప్పి ఉన్న ప్రాంతాన్ని ఎంచుకోండి:",
    filterAll: "అన్ని వ్యాయామాలు",
    filterNeck: "మెడ",
    filterBack: "వెన్ను",
    filterShoulders: "భుజాలు",
    filterLegs: "కాళ్లు & పాదాలు",
    btnStartTimer: "30 సెకన్ల టైమర్ ప్రారంభించండి",
    btnPause: "ఆపండి",
    btnReset: "మళ్లీ మొదలుపెట్టండి",
    timerSec: "సెకన్లు మిగిలి ఉన్నాయి",
    stretchComplete: "చాలా బాగుంది! కండరాల ఒత్తిడి తగ్గింది.",

    // Stretches Translation Dictionary (Telugu)
    stretch_neck_title: "మెడ వ్యాయామం (Neck Tilts & Rolls)",
    stretch_neck_step1: "తిన్నగా కూర్చోండి, భుజాలను వదులుగా ఉంచండి.",
    stretch_neck_step2: "మెల్లగా మీ కుడి చెవిని కుడి భుజం వైపు వంచండి. మెడపై కొద్దిగా ఒత్తిడి తెలిసే వరకు 5 సెకన్లు ఆగండి.",
    stretch_neck_step3: "మెల్లగా తలని ముందు వైపు తిప్పుతూ గడ్డం గుండెకు తగిలేలా చేయండి.",
    stretch_neck_step4: "మెల్లగా ఎడమ చెవిని ఎడమ భుజం వైపు వంచండి. 5 సెకన్లు ఆగి వ్యతిరేక దిశలో మళ్లీ చేయండి.",

    stretch_back_title: "కూర్చుని నడుము తిప్పే వ్యాయామం (Seated Spinal Twist)",
    stretch_back_step1: "కాళ్లు బండి ఫ్లోర్‌పై సమానంగా ఉంచి సీటులో కొద్దిగా ముందుకు కూర్చోండి.",
    stretch_back_step2: "కుడి చేతిని ఎడమ మోకాటిపై, ఎడమ చేతిని వెనుక సీటు సపోర్ట్‌పై ఉంచండి.",
    stretch_back_step3: "గాలి పీల్చి, వదులుతూ మెల్లగా శరీరాన్ని ఎడమ వైపు తిప్పి భుజంపై నుండి వెనుకకు చూడండి.",
    stretch_back_step4: "10-15 సెకన్లు ఆగండి. మెల్లగా తిన్నగా వచ్చి రెండవ వైపు కూడా ఇదే విధంగా చేయండి.",

    stretch_shoulders_title: "భుజాలు ఎత్తడం & తిప్పడం (Shoulder Shrugs & Rolls)",
    stretch_shoulders_step1: "గట్టిగా గాలి పీల్చి భుజాలను పైకి చెవుల దగ్గరకు ఎత్తండి.",
    stretch_shoulders_step2: "భుజాలను 3 సెకన్ల పాటు అలాగే గట్టిగా పట్టి ఉంచండి.",
    stretch_shoulders_step3: "గాలి వదులుతూ భుజాలను కిందకు దించి, వెనుక వైపు గుండ్రంగా తిప్పండి.",
    stretch_shoulders_step4: "ఇదే విధంగా ముందు వైపు మరియు వెనుక వైపు 5 సార్లు తిప్పండి.",

    stretch_chest_title: "స్టీరింగ్ వీల్ చెస్ట్ ఓపెనర్ (Steering Wheel Chest Opener)",
    stretch_chest_step1: "రెండు చేతులను స్టీరింగ్ వీల్‌పై 9 మరియు 3 గంటల దిశలో ఉంచండి.",
    stretch_chest_step2: "రొమ్మును ముందుకు నెట్టి, వెనుక భుజాలను ఒకదానికొకటి దగ్గరగా లాగండి.",
    stretch_chest_step3: "గడ్డాన్ని మెల్లగా పైకి ఎత్తి రొమ్ము మరియు గొంతు కండరాలను సాగదీయండి.",
    stretch_chest_step4: "గట్టిగా గాలి పీలుస్తూ 15 సెకన్లు ఆగి రొమ్ము కండరాలను రిలాక్స్ చేయండి.",

    stretch_legs_title: "మడమల పంప్ & రొటేషన్ (Ankle Pumps & Circles)",
    stretch_legs_step1: "కుడి పాదాన్ని బండి నేల నుండి కొద్దిగా పైకి లేపండి.",
    stretch_legs_step2: "పాదం బేళ్లను ముందుకు చాచండి, తర్వాత మీ ముఖం వైపుకు లాగండి. ఇలా 10 సార్లు చేయండి.",
    stretch_legs_step3: "మడమను గడియారం ముల్లు తిరిగే దిశలో 5 సార్లు, వ్యతిరేక దిశలో 5 సార్లు గుండ్రంగా తిప్పండి.",
    stretch_legs_step4: "పాదాన్ని కింద పెట్టి ఎడమ కాలితో కూడా ఇదే విధంగా చేయండి.",

    stretch_wrist_title: "మణికట్టు & వేళ్ల సాగదీత (Wrist & Finger Stretches)",
    stretch_wrist_step1: "కుడి చేతిని ముందుకు చాచండి, అరచేయి వెలుపలికి మరియు వేళ్లు పైకి ఉండేలా ఉంచండి.",
    stretch_wrist_step2: "ఎడమ చేతి సహాయంతో కుడి చేతి వేళ్లను మీ వైపుకు మెల్లగా లాగండి.",
    stretch_wrist_step3: "10 సెకన్ల ఆగిన తర్వాత వేళ్లను కిందకు వంచి మణికట్టు పైభాగాన్ని సాగదీయండి.",
    stretch_wrist_step4: "ఎడమ చేతి వేళ్లతో కూడా ఇదే విధంగా చేయండి.",

    // Find Help Page
    helpTitle: "సమీప క్లినిక్‌లు & హెల్త్ క్యాంపులు",
    helpSubtitle: "డ్రైవర్లు మరియు రవాణా కార్మికుల కోసం ప్రత్యేకంగా ఏర్పాటు చేసిన ఉచిత మరియు తక్కువ ఖర్చుతో కూడిన వైద్య శిబిరాలు, ప్రభుత్వ క్లినిక్‌లను కనుగొనండి.",
    helpNote: "గమనిక: పూర్తి వెర్షన్‌లో, ఈ పేజీ మీ ఫోన్ GPS సహాయంతో లైవ్ క్లినిక్‌లను చూపిస్తుంది. కింద ఇవ్వబడినవి మీకు దగ్గరలో ఉన్న కొన్ని నమూనా క్లినిక్‌ల వివరాలు.",
    clinicFilterAll: "అన్ని రకాలు",
    clinicFilterCamp: "ఉచిత క్యాంపులు",
    clinicFilterGov: "ప్రభుత్వ కేంద్రాలు",
    clinicFilterPhysio: "ఫిజియోథెరపిస్ట్",
    freeTag: "ఉచితం",
    lowCostTag: "తక్కువ ఖర్చు",
    btnGetDirections: "దారి చూపించు",
    btnCall: "ఫోన్ చేయండి",

    // Daily Log Page
    logTitle: "రోజువారీ డ్రైవర్ డైరీ",
    logSubtitle: "మీ రోజువారీ అలసటను డేటా రూపంలో చూసుకోండి. క్రమం తప్పకుండా విశ్రాంతి తీసుకోవడం వల్ల నొప్పి తగ్గుతుందో లేదో గమనించండి.",
    formDate: "తేదీ",
    formHours: "ఈరోజు బండి నడిపిన సమయం (గంటలు)",
    formSleep: "గత రాత్రి నిద్ర (గంటలు)",
    formPain: "నొప్పి తీవ్రత (1 = అస్సలు నొప్పి లేదు, 10 = చాలా తీవ్రమైన నొప్పి)",
    formEarnings: "ఈరోజు సంపాదన (ఐచ్ఛికం - ₹)",
    btnSaveLog: "లాగ్‌ను సేవ్ చేయండి",
    logSuccess: "లాగ్ విజయవంతంగా సేవ్ చేయబడింది!",
    chartTitle: "నొప్పి మరియు డ్రైవింగ్ గంటల పోలిక",
    chartSubtitle: "మీ పని గంటలకు మరియు శరీర నొప్పికి మధ్య ఉన్న సంబంధాన్ని తెలుసుకోండి",
    noLogsYet: "ఎటువంటి రికార్డులు లేవు. పైన ఇవ్వబడిన వివరాలను పూరించి ప్రారంభించండి!",
    painLabel: "నొప్పి స్థాయి (1-10)",
    hoursLabel: "నడిపిన గంటలు",
    streakCount: "నమోదు చేసిన రోజులు",
    streakDays: "వరుస రోజులు"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('rahat_lang') || 'en';
  });

  const changeLanguage = (langCode) => {
    setLanguage(langCode);
    localStorage.setItem('rahat_lang', langCode);
  };

  const t = (key, params = {}) => {
    let text = translations[language]?.[key] || translations['en']?.[key] || key;
    Object.keys(params).forEach(p => {
      text = text.replace(`{${p}}`, params[p]);
    });
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
